/* automatically generated by rust-bindgen */

pub const TC_VERSION_MAJOR: u32 = 2;
pub const TC_VERSION_MINOR: u32 = 7;
pub const TC_VERSION_PATCH: &'static [u8; 1usize] = b"\0";
pub const TC_VERSION_STRING: &'static [u8; 15usize] = b"gperftools 2.7\0";
pub const _MALLOC_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __STDC_NO_THREADS__: u32 = 1;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 27;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const _STDIO_H: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const ____FILE_defined: u32 = 1;
pub const __FILE_defined: u32 = 1;
pub const _BITS_LIBIO_H: u32 = 1;
pub const _BITS_G_CONFIG_H: u32 = 1;
pub const ____mbstate_t_defined: u32 = 1;
pub const _G_HAVE_MMAP: u32 = 1;
pub const _G_HAVE_MREMAP: u32 = 1;
pub const _G_IO_IO_FILE_VERSION: u32 = 131073;
pub const _G_BUFSIZ: u32 = 8192;
pub const _IO_BUFSIZ: u32 = 8192;
pub const __GNUC_VA_LIST: u32 = 1;
pub const _IO_UNIFIED_JUMPTABLES: u32 = 1;
pub const EOF: i32 = -1;
pub const _IOS_INPUT: u32 = 1;
pub const _IOS_OUTPUT: u32 = 2;
pub const _IOS_ATEND: u32 = 4;
pub const _IOS_APPEND: u32 = 8;
pub const _IOS_TRUNC: u32 = 16;
pub const _IOS_NOCREATE: u32 = 32;
pub const _IOS_NOREPLACE: u32 = 64;
pub const _IOS_BIN: u32 = 128;
pub const _IO_MAGIC: u32 = 4222418944;
pub const _OLD_STDIO_MAGIC: u32 = 4206624768;
pub const _IO_MAGIC_MASK: u32 = 4294901760;
pub const _IO_USER_BUF: u32 = 1;
pub const _IO_UNBUFFERED: u32 = 2;
pub const _IO_NO_READS: u32 = 4;
pub const _IO_NO_WRITES: u32 = 8;
pub const _IO_EOF_SEEN: u32 = 16;
pub const _IO_ERR_SEEN: u32 = 32;
pub const _IO_DELETE_DONT_CLOSE: u32 = 64;
pub const _IO_LINKED: u32 = 128;
pub const _IO_IN_BACKUP: u32 = 256;
pub const _IO_LINE_BUF: u32 = 512;
pub const _IO_TIED_PUT_GET: u32 = 1024;
pub const _IO_CURRENTLY_PUTTING: u32 = 2048;
pub const _IO_IS_APPENDING: u32 = 4096;
pub const _IO_IS_FILEBUF: u32 = 8192;
pub const _IO_BAD_SEEN: u32 = 16384;
pub const _IO_USER_LOCK: u32 = 32768;
pub const _IO_FLAGS2_MMAP: u32 = 1;
pub const _IO_FLAGS2_NOTCANCEL: u32 = 2;
pub const _IO_FLAGS2_USER_WBUF: u32 = 8;
pub const _IO_SKIPWS: u32 = 1;
pub const _IO_LEFT: u32 = 2;
pub const _IO_RIGHT: u32 = 4;
pub const _IO_INTERNAL: u32 = 8;
pub const _IO_DEC: u32 = 16;
pub const _IO_OCT: u32 = 32;
pub const _IO_HEX: u32 = 64;
pub const _IO_SHOWBASE: u32 = 128;
pub const _IO_SHOWPOINT: u32 = 256;
pub const _IO_UPPERCASE: u32 = 512;
pub const _IO_SHOWPOS: u32 = 1024;
pub const _IO_SCIENTIFIC: u32 = 2048;
pub const _IO_FIXED: u32 = 4096;
pub const _IO_UNITBUF: u32 = 8192;
pub const _IO_STDIO: u32 = 16384;
pub const _IO_DONT_CLOSE: u32 = 32768;
pub const _IO_BOOLALPHA: u32 = 65536;
pub const _IOFBF: u32 = 0;
pub const _IOLBF: u32 = 1;
pub const _IONBF: u32 = 2;
pub const BUFSIZ: u32 = 8192;
pub const SEEK_SET: u32 = 0;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const P_tmpdir: &'static [u8; 5usize] = b"/tmp\0";
pub const _BITS_STDIO_LIM_H: u32 = 1;
pub const L_tmpnam: u32 = 20;
pub const TMP_MAX: u32 = 238328;
pub const FILENAME_MAX: u32 = 4096;
pub const L_ctermid: u32 = 9;
pub const FOPEN_MAX: u32 = 16;
pub const M_MXFAST: u32 = 1;
pub const M_NLBLKS: u32 = 2;
pub const M_GRAIN: u32 = 3;
pub const M_KEEP: u32 = 4;
pub const M_TRIM_THRESHOLD: i32 = -1;
pub const M_TOP_PAD: i32 = -2;
pub const M_MMAP_THRESHOLD: i32 = -3;
pub const M_MMAP_MAX: i32 = -4;
pub const M_CHECK_ACTION: i32 = -5;
pub const M_PERTURB: i32 = -6;
pub const M_ARENA_TEST: i32 = -7;
pub const M_ARENA_MAX: i32 = -8;
pub type wchar_t = ::std::os::raw::c_int;
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: f64,
}
# [ test ]
fn bindgen_test_layout_max_align_t() {
    assert_eq!(::std::mem::size_of::<max_align_t>(),
               32usize,
               concat!("Size of: ", stringify!(max_align_t)));
    assert_eq!(unsafe {
                   &(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce1 as *const _ as
                   usize
               },
               0usize,
               concat!("Offset of field: ",
                       stringify!(max_align_t),
                       "::",
                       stringify!(__clang_max_align_nonce1)));
    assert_eq!(unsafe {
                   &(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce2 as *const _ as
                   usize
               },
               16usize,
               concat!("Offset of field: ",
                       stringify!(max_align_t),
                       "::",
                       stringify!(__clang_max_align_nonce2)));
}
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
# [ test ]
fn bindgen_test_layout___fsid_t() {
    assert_eq!(::std::mem::size_of::<__fsid_t>(),
               8usize,
               concat!("Size of: ", stringify!(__fsid_t)));
    assert_eq!(::std::mem::align_of::<__fsid_t>(),
               4usize,
               concat!("Alignment of ", stringify!(__fsid_t)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<__fsid_t>())).__val as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(__fsid_t),
                       "::",
                       stringify!(__val)));
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type __FILE = _IO_FILE;
pub type FILE = _IO_FILE;
# [ repr ( C ) ]
# [ derive ( Copy , Clone ) ]
pub struct __mbstate_t {
    pub __count: ::std::os::raw::c_int,
    pub __value: __mbstate_t__bindgen_ty_1,
}
# [ repr ( C ) ]
# [ derive ( Copy , Clone ) ]; 4usize ] , _bindgen_union_align : u32 , }# [ test ]
fn bindgen_test_layout___mbstate_t__bindgen_ty_1() {
    assert_eq!(::std::mem::size_of::<__mbstate_t__bindgen_ty_1>(),
               4usize,
               concat!("Size of: ", stringify!(__mbstate_t__bindgen_ty_1)));
    assert_eq!(::std::mem::align_of::<__mbstate_t__bindgen_ty_1>(),
               4usize,
               concat!("Alignment of ", stringify!(__mbstate_t__bindgen_ty_1)));
    assert_eq!(unsafe {
                   &(*(::std::ptr::null::<__mbstate_t__bindgen_ty_1>())).__wch as *const _ as usize
               },
               0usize,
               concat!("Offset of field: ",
                       stringify!(__mbstate_t__bindgen_ty_1),
                       "::",
                       stringify!(__wch)));
    assert_eq!(unsafe {
                   &(*(::std::ptr::null::<__mbstate_t__bindgen_ty_1>())).__wchb as *const _ as usize
               },
               0usize,
               concat!("Offset of field: ",
                       stringify!(__mbstate_t__bindgen_ty_1),
                       "::",
                       stringify!(__wchb)));
}
# [ test ]
fn bindgen_test_layout___mbstate_t() {
    assert_eq!(::std::mem::size_of::<__mbstate_t>(),
               8usize,
               concat!("Size of: ", stringify!(__mbstate_t)));
    assert_eq!(::std::mem::align_of::<__mbstate_t>(),
               4usize,
               concat!("Alignment of ", stringify!(__mbstate_t)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<__mbstate_t>())).__count as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(__mbstate_t),
                       "::",
                       stringify!(__count)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<__mbstate_t>())).__value as *const _ as usize },
               4usize,
               concat!("Offset of field: ",
                       stringify!(__mbstate_t),
                       "::",
                       stringify!(__value)));
}
# [ repr ( C ) ]
# [ derive ( Copy , Clone ) ]
pub struct _G_fpos_t {
    pub __pos: __off_t,
    pub __state: __mbstate_t,
}
# [ test ]
fn bindgen_test_layout__G_fpos_t() {
    assert_eq!(::std::mem::size_of::<_G_fpos_t>(),
               16usize,
               concat!("Size of: ", stringify!(_G_fpos_t)));
    assert_eq!(::std::mem::align_of::<_G_fpos_t>(),
               8usize,
               concat!("Alignment of ", stringify!(_G_fpos_t)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_G_fpos_t>())).__pos as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(_G_fpos_t),
                       "::",
                       stringify!(__pos)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_G_fpos_t>())).__state as *const _ as usize },
               8usize,
               concat!("Offset of field: ",
                       stringify!(_G_fpos_t),
                       "::",
                       stringify!(__state)));
}
# [ repr ( C ) ]
# [ derive ( Copy , Clone ) ]
pub struct _G_fpos64_t {
    pub __pos: __off64_t,
    pub __state: __mbstate_t,
}
# [ test ]
fn bindgen_test_layout__G_fpos64_t() {
    assert_eq!(::std::mem::size_of::<_G_fpos64_t>(),
               16usize,
               concat!("Size of: ", stringify!(_G_fpos64_t)));
    assert_eq!(::std::mem::align_of::<_G_fpos64_t>(),
               8usize,
               concat!("Alignment of ", stringify!(_G_fpos64_t)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_G_fpos64_t>())).__pos as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(_G_fpos64_t),
                       "::",
                       stringify!(__pos)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_G_fpos64_t>())).__state as *const _ as usize },
               8usize,
               concat!("Offset of field: ",
                       stringify!(_G_fpos64_t),
                       "::",
                       stringify!(__state)));
}
pub type va_list = __builtin_va_list;
pub type __gnuc_va_list = __builtin_va_list;
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct _IO_jump_t {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct _IO_marker {
    pub _next: *mut _IO_marker,
    pub _sbuf: *mut _IO_FILE,
    pub _pos: ::std::os::raw::c_int,
}
# [ test ]
fn bindgen_test_layout__IO_marker() {
    assert_eq!(::std::mem::size_of::<_IO_marker>(),
               24usize,
               concat!("Size of: ", stringify!(_IO_marker)));
    assert_eq!(::std::mem::align_of::<_IO_marker>(),
               8usize,
               concat!("Alignment of ", stringify!(_IO_marker)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_marker>()))._next as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(_IO_marker),
                       "::",
                       stringify!(_next)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_marker>()))._sbuf as *const _ as usize },
               8usize,
               concat!("Offset of field: ",
                       stringify!(_IO_marker),
                       "::",
                       stringify!(_sbuf)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_marker>()))._pos as *const _ as usize },
               16usize,
               concat!("Offset of field: ",
                       stringify!(_IO_marker),
                       "::",
                       stringify!(_pos)));
}
pub const __codecvt_result___codecvt_ok: __codecvt_result = 0;
pub const __codecvt_result___codecvt_partial: __codecvt_result = 1;
pub const __codecvt_result___codecvt_error: __codecvt_result = 2;
pub const __codecvt_result___codecvt_noconv: __codecvt_result = 3;
pub type __codecvt_result = u32;
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _flags2: ::std::os::raw::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub __pad1: *mut ::std::os::raw::c_void,
    pub __pad2: *mut ::std::os::raw::c_void,
    pub __pad3: *mut ::std::os::raw::c_void,
    pub __pad4: *mut ::std::os::raw::c_void,
    pub __pad5: usize,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
# [ test ]
fn bindgen_test_layout__IO_FILE() {
    assert_eq!(::std::mem::size_of::<_IO_FILE>(),
               216usize,
               concat!("Size of: ", stringify!(_IO_FILE)));
    assert_eq!(::std::mem::align_of::<_IO_FILE>(),
               8usize,
               concat!("Alignment of ", stringify!(_IO_FILE)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._flags as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_flags)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_read_ptr as *const _ as usize },
               8usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_read_ptr)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_read_end as *const _ as usize },
               16usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_read_end)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_read_base as *const _ as usize },
               24usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_read_base)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_write_base as *const _ as usize },
               32usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_write_base)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_write_ptr as *const _ as usize },
               40usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_write_ptr)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_write_end as *const _ as usize },
               48usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_write_end)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_buf_base as *const _ as usize },
               56usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_buf_base)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_buf_end as *const _ as usize },
               64usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_buf_end)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_save_base as *const _ as usize },
               72usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_save_base)));
    assert_eq!(unsafe {
                   &(*(::std::ptr::null::<_IO_FILE>()))._IO_backup_base as *const _ as usize
               },
               80usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_backup_base)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._IO_save_end as *const _ as usize },
               88usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_IO_save_end)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._markers as *const _ as usize },
               96usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_markers)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._chain as *const _ as usize },
               104usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_chain)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._fileno as *const _ as usize },
               112usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_fileno)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._flags2 as *const _ as usize },
               116usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_flags2)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._old_offset as *const _ as usize },
               120usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_old_offset)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._cur_column as *const _ as usize },
               128usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_cur_column)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._vtable_offset as *const _ as usize },
               130usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_vtable_offset)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._shortbuf as *const _ as usize },
               131usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_shortbuf)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._lock as *const _ as usize },
               136usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_lock)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._offset as *const _ as usize },
               144usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_offset)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>())).__pad1 as *const _ as usize },
               152usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(__pad1)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>())).__pad2 as *const _ as usize },
               160usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(__pad2)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>())).__pad3 as *const _ as usize },
               168usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(__pad3)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>())).__pad4 as *const _ as usize },
               176usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(__pad4)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>())).__pad5 as *const _ as usize },
               184usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(__pad5)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._mode as *const _ as usize },
               192usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_mode)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<_IO_FILE>()))._unused2 as *const _ as usize },
               196usize,
               concat!("Offset of field: ",
                       stringify!(_IO_FILE),
                       "::",
                       stringify!(_unused2)));
}
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct _IO_FILE_plus {
    _unused: [u8; 0],
}
extern "C" {# [ link_name = "\u{1}_IO_2_1_stdin_" ]    pub static mut _IO_2_1_stdin_: _IO_FILE_plus;
}
extern "C" {# [ link_name = "\u{1}_IO_2_1_stdout_" ]    pub static mut _IO_2_1_stdout_: _IO_FILE_plus;
}
extern "C" {# [ link_name = "\u{1}_IO_2_1_stderr_" ]    pub static mut _IO_2_1_stderr_: _IO_FILE_plus;
}
pub type __io_read_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie: *mut ::std::os::raw::c_void,
                                               __buf: *mut ::std::os::raw::c_char,
                                               __nbytes: usize)
                                               -> __ssize_t>;
pub type __io_write_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie: *mut ::std::os::raw::c_void,
                                               __buf: *const ::std::os::raw::c_char,
                                               __n: usize)
                                               -> __ssize_t>;
pub type __io_seek_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie: *mut ::std::os::raw::c_void,
                                               __pos: *mut __off64_t,
                                               __w: ::std::os::raw::c_int)
                                               -> ::std::os::raw::c_int>;
pub type __io_close_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie: *mut ::std::os::raw::c_void)
                                               -> ::std::os::raw::c_int>;
extern "C" {
    pub fn __underflow(arg1: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __uflow(arg1: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __overflow(arg1: *mut _IO_FILE, arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_getc(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_putc(__c: ::std::os::raw::c_int, __fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_feof(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_ferror(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_peekc_locked(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_flockfile(arg1: *mut _IO_FILE);
}
extern "C" {
    pub fn _IO_funlockfile(arg1: *mut _IO_FILE);
}
extern "C" {
    pub fn _IO_ftrylockfile(arg1: *mut _IO_FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_vfscanf(arg1: *mut _IO_FILE,
                       arg2: *const ::std::os::raw::c_char,
                       arg3: *mut __va_list_tag,
                       arg4: *mut ::std::os::raw::c_int)
                       -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_vfprintf(arg1: *mut _IO_FILE,
                        arg2: *const ::std::os::raw::c_char,
                        arg3: *mut __va_list_tag)
                        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _IO_padn(arg1: *mut _IO_FILE,
                    arg2: ::std::os::raw::c_int,
                    arg3: __ssize_t)
                    -> __ssize_t;
}
extern "C" {
    pub fn _IO_sgetn(arg1: *mut _IO_FILE, arg2: *mut ::std::os::raw::c_void, arg3: usize) -> usize;
}
extern "C" {
    pub fn _IO_seekoff(arg1: *mut _IO_FILE,
                       arg2: __off64_t,
                       arg3: ::std::os::raw::c_int,
                       arg4: ::std::os::raw::c_int)
                       -> __off64_t;
}
extern "C" {
    pub fn _IO_seekpos(arg1: *mut _IO_FILE,
                       arg2: __off64_t,
                       arg3: ::std::os::raw::c_int)
                       -> __off64_t;
}
extern "C" {
    pub fn _IO_free_backup_area(arg1: *mut _IO_FILE);
}
pub type off_t = __off_t;
pub type fpos_t = _G_fpos_t;
extern "C" {# [ link_name = "\u{1}stdin" ]    pub static mut stdin: *mut _IO_FILE;
}
extern "C" {# [ link_name = "\u{1}stdout" ]    pub static mut stdout: *mut _IO_FILE;
}
extern "C" {# [ link_name = "\u{1}stderr" ]    pub static mut stderr: *mut _IO_FILE;
}
extern "C" {
    pub fn remove(__filename: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rename(__old: *const ::std::os::raw::c_char,
                  __new: *const ::std::os::raw::c_char)
                  -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn renameat(__oldfd: ::std::os::raw::c_int,
                    __old: *const ::std::os::raw::c_char,
                    __newfd: ::std::os::raw::c_int,
                    __new: *const ::std::os::raw::c_char)
                    -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tmpfile() -> *mut FILE;
}
extern "C" {
    pub fn tmpnam(__s: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn tmpnam_r(__s: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn tempnam(__dir: *const ::std::os::raw::c_char,
                   __pfx: *const ::std::os::raw::c_char)
                   -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn fclose(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fflush(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fflush_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fopen(__filename: *const ::std::os::raw::c_char,
                 __modes: *const ::std::os::raw::c_char)
                 -> *mut FILE;
}
extern "C" {
    pub fn freopen(__filename: *const ::std::os::raw::c_char,
                   __modes: *const ::std::os::raw::c_char,
                   __stream: *mut FILE)
                   -> *mut FILE;
}
extern "C" {
    pub fn fdopen(__fd: ::std::os::raw::c_int,
                  __modes: *const ::std::os::raw::c_char)
                  -> *mut FILE;
}
extern "C" {
    pub fn fmemopen(__s: *mut ::std::os::raw::c_void,
                    __len: usize,
                    __modes: *const ::std::os::raw::c_char)
                    -> *mut FILE;
}
extern "C" {
    pub fn open_memstream(__bufloc: *mut *mut ::std::os::raw::c_char,
                          __sizeloc: *mut usize)
                          -> *mut FILE;
}
extern "C" {
    pub fn setbuf(__stream: *mut FILE, __buf: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn setvbuf(__stream: *mut FILE,
                   __buf: *mut ::std::os::raw::c_char,
                   __modes: ::std::os::raw::c_int,
                   __n: usize)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn setbuffer(__stream: *mut FILE, __buf: *mut ::std::os::raw::c_char, __size: usize);
}
extern "C" {
    pub fn setlinebuf(__stream: *mut FILE);
}
extern "C" {
    pub fn fprintf(__stream: *mut FILE,
                   __format: *const ::std::os::raw::c_char,
                   ...)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn printf(__format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn sprintf(__s: *mut ::std::os::raw::c_char,
                   __format: *const ::std::os::raw::c_char,
                   ...)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vfprintf(__s: *mut FILE,
                    __format: *const ::std::os::raw::c_char,
                    __arg: *mut __va_list_tag)
                    -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vprintf(__format: *const ::std::os::raw::c_char,
                   __arg: *mut __va_list_tag)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vsprintf(__s: *mut ::std::os::raw::c_char,
                    __format: *const ::std::os::raw::c_char,
                    __arg: *mut __va_list_tag)
                    -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn snprintf(__s: *mut ::std::os::raw::c_char,
                    __maxlen: usize,
                    __format: *const ::std::os::raw::c_char,
                    ...)
                    -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vsnprintf(__s: *mut ::std::os::raw::c_char,
                     __maxlen: usize,
                     __format: *const ::std::os::raw::c_char,
                     __arg: *mut __va_list_tag)
                     -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vdprintf(__fd: ::std::os::raw::c_int,
                    __fmt: *const ::std::os::raw::c_char,
                    __arg: *mut __va_list_tag)
                    -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn dprintf(__fd: ::std::os::raw::c_int,
                   __fmt: *const ::std::os::raw::c_char,
                   ...)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fscanf(__stream: *mut FILE,
                  __format: *const ::std::os::raw::c_char,
                  ...)
                  -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn scanf(__format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn sscanf(__s: *const ::std::os::raw::c_char,
                  __format: *const ::std::os::raw::c_char,
                  ...)
                  -> ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}__isoc99_fscanf" ]    pub fn fscanf1(__stream: *mut FILE,
                   __format: *const ::std::os::raw::c_char,
                   ...)
                   -> ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}__isoc99_scanf" ]    pub fn scanf1(__format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}__isoc99_sscanf" ]    pub fn sscanf1(__s: *const ::std::os::raw::c_char,
                   __format: *const ::std::os::raw::c_char,
                   ...)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vfscanf(__s: *mut FILE,
                   __format: *const ::std::os::raw::c_char,
                   __arg: *mut __va_list_tag)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vscanf(__format: *const ::std::os::raw::c_char,
                  __arg: *mut __va_list_tag)
                  -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vsscanf(__s: *const ::std::os::raw::c_char,
                   __format: *const ::std::os::raw::c_char,
                   __arg: *mut __va_list_tag)
                   -> ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}__isoc99_vfscanf" ]    pub fn vfscanf1(__s: *mut FILE,
                    __format: *const ::std::os::raw::c_char,
                    __arg: *mut __va_list_tag)
                    -> ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}__isoc99_vscanf" ]    pub fn vscanf1(__format: *const ::std::os::raw::c_char,
                   __arg: *mut __va_list_tag)
                   -> ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}__isoc99_vsscanf" ]    pub fn vsscanf1(__s: *const ::std::os::raw::c_char,
                    __format: *const ::std::os::raw::c_char,
                    __arg: *mut __va_list_tag)
                    -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fgetc(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn getc(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn getchar() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn getc_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn getchar_unlocked() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fgetc_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fputc(__c: ::std::os::raw::c_int, __stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn putc(__c: ::std::os::raw::c_int, __stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn putchar(__c: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fputc_unlocked(__c: ::std::os::raw::c_int,
                          __stream: *mut FILE)
                          -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn putc_unlocked(__c: ::std::os::raw::c_int, __stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn putchar_unlocked(__c: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn getw(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn putw(__w: ::std::os::raw::c_int, __stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fgets(__s: *mut ::std::os::raw::c_char,
                 __n: ::std::os::raw::c_int,
                 __stream: *mut FILE)
                 -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn __getdelim(__lineptr: *mut *mut ::std::os::raw::c_char,
                      __n: *mut usize,
                      __delimiter: ::std::os::raw::c_int,
                      __stream: *mut FILE)
                      -> __ssize_t;
}
extern "C" {
    pub fn getdelim(__lineptr: *mut *mut ::std::os::raw::c_char,
                    __n: *mut usize,
                    __delimiter: ::std::os::raw::c_int,
                    __stream: *mut FILE)
                    -> __ssize_t;
}
extern "C" {
    pub fn getline(__lineptr: *mut *mut ::std::os::raw::c_char,
                   __n: *mut usize,
                   __stream: *mut FILE)
                   -> __ssize_t;
}
extern "C" {
    pub fn fputs(__s: *const ::std::os::raw::c_char, __stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn puts(__s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ungetc(__c: ::std::os::raw::c_int, __stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fread(__ptr: *mut ::std::os::raw::c_void,
                 __size: usize,
                 __n: usize,
                 __stream: *mut FILE)
                 -> usize;
}
extern "C" {
    pub fn fwrite(__ptr: *const ::std::os::raw::c_void,
                  __size: usize,
                  __n: usize,
                  __s: *mut FILE)
                  -> usize;
}
extern "C" {
    pub fn fread_unlocked(__ptr: *mut ::std::os::raw::c_void,
                          __size: usize,
                          __n: usize,
                          __stream: *mut FILE)
                          -> usize;
}
extern "C" {
    pub fn fwrite_unlocked(__ptr: *const ::std::os::raw::c_void,
                           __size: usize,
                           __n: usize,
                           __stream: *mut FILE)
                           -> usize;
}
extern "C" {
    pub fn fseek(__stream: *mut FILE,
                 __off: ::std::os::raw::c_long,
                 __whence: ::std::os::raw::c_int)
                 -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ftell(__stream: *mut FILE) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn rewind(__stream: *mut FILE);
}
extern "C" {
    pub fn fseeko(__stream: *mut FILE,
                  __off: __off_t,
                  __whence: ::std::os::raw::c_int)
                  -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ftello(__stream: *mut FILE) -> __off_t;
}
extern "C" {
    pub fn fgetpos(__stream: *mut FILE, __pos: *mut fpos_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fsetpos(__stream: *mut FILE, __pos: *const fpos_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn clearerr(__stream: *mut FILE);
}
extern "C" {
    pub fn feof(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ferror(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn clearerr_unlocked(__stream: *mut FILE);
}
extern "C" {
    pub fn feof_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ferror_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn perror(__s: *const ::std::os::raw::c_char);
}
extern "C" {# [ link_name = "\u{1}sys_nerr" ]    pub static mut sys_nerr: ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}sys_errlist" ]    pub static mut sys_errlist: [*const ::std::os::raw::c_char; 0usize];
}
extern "C" {
    pub fn fileno(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fileno_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn popen(__command: *const ::std::os::raw::c_char,
                 __modes: *const ::std::os::raw::c_char)
                 -> *mut FILE;
}
extern "C" {
    pub fn pclose(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ctermid(__s: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn flockfile(__stream: *mut FILE);
}
extern "C" {
    pub fn ftrylockfile(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn funlockfile(__stream: *mut FILE);
}
extern "C" {
    pub fn malloc(__size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn calloc(__nmemb: usize, __size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn realloc(__ptr: *mut ::std::os::raw::c_void,
                   __size: usize)
                   -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn reallocarray(__ptr: *mut ::std::os::raw::c_void,
                        __nmemb: usize,
                        __size: usize)
                        -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn free(__ptr: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn memalign(__alignment: usize, __size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn valloc(__size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn pvalloc(__size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {# [ link_name = "\u{1}__morecore" ]    ;
}
extern "C" {
    pub fn __default_morecore(__size: isize) -> *mut ::std::os::raw::c_void;
}
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct mallinfo {
    pub arena: ::std::os::raw::c_int,
    pub ordblks: ::std::os::raw::c_int,
    pub smblks: ::std::os::raw::c_int,
    pub hblks: ::std::os::raw::c_int,
    pub hblkhd: ::std::os::raw::c_int,
    pub usmblks: ::std::os::raw::c_int,
    pub fsmblks: ::std::os::raw::c_int,
    pub uordblks: ::std::os::raw::c_int,
    pub fordblks: ::std::os::raw::c_int,
    pub keepcost: ::std::os::raw::c_int,
}
# [ test ]
fn bindgen_test_layout_mallinfo() {
    assert_eq!(::std::mem::size_of::<mallinfo>(),
               40usize,
               concat!("Size of: ", stringify!(mallinfo)));
    assert_eq!(::std::mem::align_of::<mallinfo>(),
               4usize,
               concat!("Alignment of ", stringify!(mallinfo)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).arena as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(arena)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).ordblks as *const _ as usize },
               4usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(ordblks)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).smblks as *const _ as usize },
               8usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(smblks)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).hblks as *const _ as usize },
               12usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(hblks)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).hblkhd as *const _ as usize },
               16usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(hblkhd)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).usmblks as *const _ as usize },
               20usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(usmblks)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).fsmblks as *const _ as usize },
               24usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(fsmblks)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).uordblks as *const _ as usize },
               28usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(uordblks)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).fordblks as *const _ as usize },
               32usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(fordblks)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<mallinfo>())).keepcost as *const _ as usize },
               36usize,
               concat!("Offset of field: ",
                       stringify!(mallinfo),
                       "::",
                       stringify!(keepcost)));
}
extern "C" {
    pub fn mallinfo() -> mallinfo;
}
extern "C" {
    pub fn mallopt(__param: ::std::os::raw::c_int,
                   __val: ::std::os::raw::c_int)
                   -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn malloc_trim(__pad: usize) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn malloc_usable_size(__ptr: *mut ::std::os::raw::c_void) -> usize;
}
extern "C" {
    pub fn malloc_stats();
}
extern "C" {
    pub fn malloc_info(__options: ::std::os::raw::c_int, __fp: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {# [ link_name = "\u{1}__free_hook" ]    ;
}
extern "C" {# [ link_name = "\u{1}__malloc_hook" ]    ;
}
extern "C" {# [ link_name = "\u{1}__realloc_hook" ]    ;
}
extern "C" {# [ link_name = "\u{1}__memalign_hook" ]    ;
}
extern "C" {# [ link_name = "\u{1}__after_morecore_hook" ]    pub static mut __after_morecore_hook: ::std::option::Option<unsafe extern "C" fn()>;
}
extern "C" {
    pub fn __malloc_check_init();
}
extern "C" {
    pub fn tc_version(major: *mut ::std::os::raw::c_int,
                      minor: *mut ::std::os::raw::c_int,
                      patch: *mut *const ::std::os::raw::c_char)
                      -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn tc_malloc(size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tc_malloc_skip_new_handler(size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tc_free(ptr: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn tc_free_sized(ptr: *mut ::std::os::raw::c_void, size: usize);
}
extern "C" {
    pub fn tc_realloc(ptr: *mut ::std::os::raw::c_void,
                      size: usize)
                      -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tc_calloc(nmemb: usize, size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tc_cfree(ptr: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn tc_memalign(__alignment: usize, __size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tc_posix_memalign(ptr: *mut *mut ::std::os::raw::c_void,
                             align: usize,
                             size: usize)
                             -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tc_valloc(__size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tc_pvalloc(__size: usize) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tc_malloc_stats();
}
extern "C" {
    pub fn tc_mallopt(cmd: ::std::os::raw::c_int,
                      value: ::std::os::raw::c_int)
                      -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tc_mallinfo() -> mallinfo;
}
extern "C" {
    pub fn tc_malloc_size(ptr: *mut ::std::os::raw::c_void) -> usize;
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
# [ test ]
fn bindgen_test_layout___va_list_tag() {
    assert_eq!(::std::mem::size_of::<__va_list_tag>(),
               24usize,
               concat!("Size of: ", stringify!(__va_list_tag)));
    assert_eq!(::std::mem::align_of::<__va_list_tag>(),
               8usize,
               concat!("Alignment of ", stringify!(__va_list_tag)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<__va_list_tag>())).gp_offset as *const _ as usize },
               0usize,
               concat!("Offset of field: ",
                       stringify!(__va_list_tag),
                       "::",
                       stringify!(gp_offset)));
    assert_eq!(unsafe { &(*(::std::ptr::null::<__va_list_tag>())).fp_offset as *const _ as usize },
               4usize,
               concat!("Offset of field: ",
                       stringify!(__va_list_tag),
                       "::",
                       stringify!(fp_offset)));
    assert_eq!(unsafe {
                   &(*(::std::ptr::null::<__va_list_tag>())).overflow_arg_area as *const _ as usize
               },
               8usize,
               concat!("Offset of field: ",
                       stringify!(__va_list_tag),
                       "::",
                       stringify!(overflow_arg_area)));
    assert_eq!(unsafe {
                   &(*(::std::ptr::null::<__va_list_tag>())).reg_save_area as *const _ as usize
               },
               16usize,
               concat!("Offset of field: ",
                       stringify!(__va_list_tag),
                       "::",
                       stringify!(reg_save_area)));
}
